### ISSUE TITLE
Look into switching to jpm for packaging

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/buffer-firefox#10]
With Firefox > 34 we can now use the jpm tool instead of the old SDK, this may be a bit cleaner instead of cloning the SDK. jpm also gets updated more frequently it looks like!

https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Getting_Started_(jpm)

**Comment by philippe-git** [comment]
We're now using WebExtensions! 🙌
