### ISSUE TITLE
Remove legacy code

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/buffer-firefox#11]
When uploading the add-on, we get warnings about using legacy code from the SDK. We may have to remove this soon, it's mostly for old versions and we'd have to do it if we [switch to using jpm](https://github.com/bufferapp/buffer-firefox/issues/10). 

This code is now contained in [legacy.js](https://github.com/bufferapp/buffer-firefox/blob/master/firefox/lib/legacy.js) after #8.

**Comment by philippe-git** [comment]
Now using a different codebase, closing
