### ISSUE TITLE
Look further into setTimeout warnings

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/buffer-firefox#12]
Mozilla warns against using setTimeout everywhere in [bufferapp/buffer-extension-shared](https://github.com/bufferapp/buffer-extension-shared):

> `setTimeout` called in potentially dangerous manner
>     Signing severity: high
> 
> Warning: In order to prevent vulnerabilities, the `setTimeout` and `setInterval` functions should be called only with function expressions as their first argument.

We may want to change how these check loops work, potentially wrapping this and make a re-usable check loop function.

**Comment by philippe-git** [comment]
Now using a different codebase and not seeing those warnings anymore, closing
