### ISSUE TITLE
Misaligned Buffer Icon on Twitter

### ISSUE THREAD

**Issue by theprivileges** [bufferapp/buffer-firefox#14]
I think Twitter updated their layout and it caused the buffer icon to misalign with the rest of the `.ProfileTweetAction` icons.  The buttons now have a `.profileTweet-actonButton` class applied to them.

![screen shot 2015-10-23 at 09 21 58](https://cloud.githubusercontent.com/assets/844516/10698778/a3e8c31a-7967-11e5-9278-eecc57987242.png)
## Application Basics

Name: Firefox
Version: 41.0.2
Build ID: 20151014143721
Update Channel: release
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0
Multiprocess Windows: 0/1 (default: false)
## Crash Reports for the Last 3 Days

All Crash Reports
## Extensions

Name: Advertising Cookie Opt-out
Version: 1.5
Enabled: true
ID: optout@google.com

Name: Buffer for Firefox
Version: 2.12.7
Enabled: true
ID: firefox@buffer

Name: Firebug
Version: 2.0.12
Enabled: true
ID: firebug@software.joehewitt.com

Name: LastPass
Version: 3.2.16a
Enabled: true
ID: support@lastpass.com

Name: Web Developer
Version: 1.2.5.1-signed
Enabled: true
ID: {c45c406e-ab73-11d8-be73-000a95be3b12}
## Graphics

Asynchronous Pan/Zoom: none
Device ID: 0x6810
GPU Accelerated Windows: 1/1 OpenGL (OMTC)
Supports Hardware H264 Decoding: false
Vendor ID: 0x1002
WebGL Renderer: ATI Technologies Inc. -- AMD Radeon HD - FirePro D300 OpenGL Engine
windowLayerManagerRemote: true
AzureCanvasBackend: skia
AzureContentBackend: quartz
AzureFallbackCanvasBackend: none
AzureSkiaAccelerated: 0
## Important Modified Preferences

accessibility.typeaheadfind.flashBar: 0
browser.cache.disk.capacity: 358400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 3
browser.download.importedFromSqlite: true
browser.places.smartBookmarksVersion: 7
browser.privatebrowsing.autostart: true
browser.search.useDBForOrder: true
browser.sessionstore.upgradeBackup.latestBuildID: 20150630154324
browser.startup.homepage_override.buildID: 20151014143721
browser.startup.homepage_override.mstone: 41.0.2
browser.zoom.full: false
dom.apps.reset-permissions: true
dom.mozApps.used: true
extensions.lastAppVersion: 41.0.2
font.internaluseonly.changed: true
gfx.blacklist.direct2d: 3
gfx.blacklist.layers.direct3d9: 3
media.gmp-gmpopenh264.lastUpdate: 1438623604
media.gmp-gmpopenh264.version: 1.4
media.gmp-manager.buildID: 20151014143721
media.gmp-manager.lastCheck: 1445548131
network.auth.allow-subresource-auth: 2
network.cookie.cookieBehavior: 3
network.cookie.prefsMigrated: true
network.predictor.cleaned-up: true
places.database.lastMaintenance: 1445491695
places.history.expiration.transient_current_max_pages: 104858
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.importedState: true
plugin.state.nplastpass: 2
privacy.cpd.offlineApps: true
privacy.cpd.siteSettings: true
privacy.donottrackheader.enabled: true
privacy.sanitize.migrateFx3Prefs: true
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1444252405
## JavaScript

Incremental GC: true
## Accessibility

Activated: false
Prevent Accessibility: 0
## Library Versions

NSPR
Expected minimum version: 4.10.8
Version in use: 4.10.8

NSS
Expected minimum version: 3.19.2 Basic ECC
Version in use: 3.19.2 Basic ECC

NSSSMIME
Expected minimum version: 3.19.2 Basic ECC
Version in use: 3.19.2 Basic ECC

NSSSSL
Expected minimum version: 3.19.2 Basic ECC
Version in use: 3.19.2 Basic ECC

NSSUTIL
Expected minimum version: 3.19.2
Version in use: 3.19.2

**Comment by philippe-git** [comment]
Hey @theprivileges, sorry for dropping the ball and not following up on this one! We did update the extension shortly after spotting this, thanks for letting us know! (And please continue sharing any issues/thoughts, they're always very welcome!)
