### ISSUE TITLE
Crashes Tabs When enabled with E10s

### ISSUE THREAD

**Issue by Nidre** [bufferapp/buffer-firefox#15]
Disabling Buffer resolves crashing tabs issue.
## Application Basics

Name: Firefox
Version: 47.0a1
Build ID: 20160210071115
Update Channel: nightly
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
Multiprocess Windows: 1/1 (Enabled by user)
Safe Mode: false
## Extensions

Name: Buffer
Version: 2.13.17
Enabled: false
ID: jid1-zUyU7TGKwejAyA@jetpack
## Graphics

Adapter Description: NVIDIA GeForce GTX 980M
Adapter Drivers: nvd3dumx,nvwgf2umx,nvwgf2umx,nvwgf2umx nvd3dum,nvwgf2um,nvwgf2um,nvwgf2um
Adapter RAM: 4095
Asynchronous Pan/Zoom: wheel input enabled; touch input enabled
Device ID: 0x1617
Direct2D Enabled: true
DirectWrite Enabled: true (10.0.10586.0)
Driver Date: 1-22-2016
Driver Version: 10.18.13.6175
GPU #2 Active: false
GPU Accelerated Windows: 1/1 Direct3D 11 (OMTC)
Subsys ID: 11571462
Supports Hardware H264 Decoding: Yes
Vendor ID: 0x10de
WebGL Renderer: Google Inc. -- ANGLE (NVIDIA GeForce GTX 980M Direct3D11 vs_5_0 ps_5_0)
windowLayerManagerRemote: true
AzureCanvasBackend: direct2d 1.1
AzureContentBackend: direct2d 1.1
AzureFallbackCanvasBackend: cairo
AzureSkiaAccelerated: 0

**Comment by philippe-git** [comment]
Hey @Nidre, looking back to the [Bugzilla thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1059855), this might have been a side-effect of using the Selection API with e10s enabled. Moving to WebExtensions almost certainly solved this issue as much as it did #13 :) I'll close this issue for now, but could you confirm that you're not running into any additional crashes with [3.0.3 and up](https://buffer.com/extensions)?
