### ISSUE TITLE
addon not activated on ffx launch

### ISSUE THREAD

**Issue by Geobert** [bufferapp/buffer-firefox#17]
2.13.37
ffx nightly 53.0a1 (2016-12-30) (64-bit) Wind 10 64b e10s activated

need to disable/enable the addon to make it work with e10s.

**Comment by philippe-git** [comment]
Thanks for letting us know @Geobert! I think this is the same issue as #13, and is fixed in 3.0.3, which will be up on AMO soon (currently pending review), and is already available on our self-hosted https://buffer.com/extensions :)

**Comment by Geobert** [comment]
fixed confirmed on ffx nightly 54.0a1 (2017-01-25) (64-bit)
