### ISSUE TITLE
Firefox's XML Formatting 'Broken' After Buffer Installed

### ISSUE THREAD

**Issue by LTheobald** [bufferapp/buffer-firefox#9]
Hi all,

After I install Buffer for Firefox, XML doesn't get properly formatted in my browser. Steps to recreate:

1. Start with a clean Firefox install (so there's no add-ons)
1. Visit a page returning XML (e.g. https://dl.dropboxusercontent.com/u/135227/test.xml). The XML will be pretty printed.
1. Install Buffer for Firefox v2.10.2. I did this from https://addons.mozilla.org/en-us/firefox/addon/buffer-for-firefox/
1. Revisit the page from point 2. The pretty printing is gone & XML elements are no longer showing. It looks like the response is being rendered as HTML instead of XML

![example](https://cloud.githubusercontent.com/assets/20010/7041617/c5c284ca-ddd2-11e4-8c97-8a54b83a843f.png)

If I get a change, I'll see if I can find the reason why & put a pull request in but that might not happen till tonight for me (in the UK).

**Comment by djfarrelly** [comment]
Hey @LTheobald, this same issue was reported a few weeks ago and we [added some exclude options to our page modifications to fix this issue](https://github.com/bufferapp/buffer-firefox/blob/master/firefox/lib/main.js#L237-L253). Maybe we need more page mod's excluded?

Let me know if you find anything out! Thanks :)
